#Hugo configuration
title = "asdf"
baseURL = "https:\/\/https:\/\/www.TEST.COm"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
firstpartycookies = true
cookiedomain = "TEST.COm"
